# BotBot Configuration override file
!Config

    APP_NAME: 'BotBot'

    SOURCE: !Config
        CUSTOM: 'bijij/botbot'

    BOT: !Config
        PREFIX: "(bb)"
        INTENTS:
            guilds: yes
            members: yes
            bans: yes
            emojis: yes
            integrations: yes
            webhooks: yes
            invites: yes
            voice_states: yes
            presences: yes
            messages: yes
            reactions: yes
            typing: yes

    DATABASE: !Config
        APPLICATION_NAME: 'BotBot'

    LOGGING: !Config
        LOG_LEVEL: "INFO"
        GLOBAL_LOG_LEVEL: "WARNING"
        LOG_TO_FILE: yes

    EXTENSIONS:

        # Core Extensions
        cogs.core.whitelist: ~

        # Logging extensions
        cogs.logging.core: ~
        cogs.logging.status: ~
        cogs.logging.voice: ~
        cogs.logging.tags: ~

        # Meme extensions
        cogs.memes.bottom: ~        
        cogs.memes.markov: ~
        cogs.memes.timecard: ~
        cogs.memes.bot_status: ~
        cogs.memes.imagine: !Config
            TITLE_FONT: 'res/GintoNord-Black.ttf'
            BYLINE_FONT: 'res/GintoNord-Medium.ttf'

        # Game Extensions
        cogs.games.connect_four: ~
        cogs.games.boggle: ~
        cogs.games.foggle: ~
        cogs.games.minesweeper: ~
        cogs.games.tic_tac_toe: ~
        cogs.games.secret_hitler: ~

        cogs.games.gameboy: !Config
            RENDER_CHANNEL: !Channel 551765961070608384 847779308793233428

        cogs.games.voltorb_flip: !Config
            RENDER_CHANNEL: !Channel 551765961070608384 847779308793233428

        # General Extensions
        cogs.reminders: ~
        
        # Moderation Extensions
        # moderation.logs: ~
        cogs.moderation.spam: ~
        cogs.moderation.tools: ~

    REPOSITORY_URL: https://github.com/bijij/BotBot

    # Consts
    DPY_VOICE_GENERAL: !Channel 336642139381301249 741656304359178271
    DISCORD_PY: !Guild 336642139381301249
    R_DANNY: !User 80528701850124288
